version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - internal

  broker:
    image: wurstmeister/kafka
    container_name: broker
    hostname: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://broker:9090, A://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://broker:9090, A://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT, A:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS : 5
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 60000
      KAFKA_CREATE_TOPICS_SEPARATOR: ","
      KAFKA_CREATE_TOPICS: "test_input:32:1,test_output:32:1"
    restart: always
    depends_on:
      - zookeeper
    networks:
      - internal

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - zookeeper
      - broker
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - internal

networks:
  internal:
    driver: bridge