name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Dependencies
      run: | 
        echo "Download Dependencies"
        go mod tidy
        go mod vendor

    - name: Benchmark
      run: | 
        echo "Benchmark Expression Evaluation libraries"
        cd  expression-evaluation && go test -bench=. -benchmem -count 5 -benchtime=10000x > results/results.out
        echo "Benchmark In-Memory Cache libraries"
        cd  in-memory-cache && go test -bench=. -benchmem -count 5 -benchtime=100000x > results/results.out

