name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Dependencies
      run: go mod tidy
      run: go mod vendor

    - name: Test
      run: cd  expression-evaluation && go test -bench=. -benchmem -count 5 -benchtime=10000x > results/results.out
      run: cd  in-memory-cache && go test -bench=. -benchmem -count 5 -benchtime=100000x > results/results.out

